### ISSUE TITLE
Upating the image, results in a boot loop, failing to boot. 

### ISSUE THREAD

**Issue by MxD-js** [linuxserver/docker-mariadb#85] opened 2021-06-03 15:24 UTC
After updating the image, I get this when start it up, it continues to loop over and over. 

`
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes

-------------------------------------

          _         ()

         | |  ___   _    __

         | | / __| | |  /  \ 

         | | \__ \ | | | () |

         |_| |___/ |_|  \__/

Brought to you by linuxserver.io

-------------------------------------

To support LSIO projects visit:

https://www.linuxserver.io/donate/

-------------------------------------

GID/UID

-------------------------------------

User uid:    1000

User gid:    1000

-------------------------------------

[cont-init.d] 10-adduser: exited 0.

[cont-init.d] 30-config: executing... 

[cont-init.d] 30-config: exited 0.

[cont-init.d] 40-initialise-db: executing... 

[cont-init.d] 40-initialise-db: exited 0.

[cont-init.d] 90-warning: executing... 

******************************************************

******************************************************

*                                                    *

*                                                    *

*          This image will soon be rebased           *

*               from ubuntu to alpine.               *

*       Please be aware, this may cause issues       *

*     It is strongly recommended to make backups     *

*         of your config and databases before        *

*       updating your image to the alpine base.      *

*                                                    *

*                                                    *

******************************************************

******************************************************

[cont-init.d] 90-warning: exited 0.

[cont-init.d] 99-custom-scripts: executing... 

[custom-init] no custom files found exiting...

[cont-init.d] 99-custom-scripts: exited 0.

[cont-init.d] done.

[services.d] starting services

[services.d] done.

210603 16:16:40 mysqld_safe Logging to syslog.

210603 16:16:40 mysqld_safe Starting mysqld daemon with databases from /config/databases

210603 16:16:41 mysqld_safe Logging to syslog.

210603 16:16:41 mysqld_safe Starting mysqld daemon with databases from /config/databases

210603 16:16:43 mysqld_safe Logging to syslog.

210603 16:16:43 mysqld_safe Starting mysqld daemon with databases from /config/databases

210603 16:16:44 mysqld_safe Logging to syslog.

210603 16:16:44 mysqld_safe Starting mysqld daemon with databases from /config/databases
`

**Comment by j0nnymoe** [comment] 2021-06-03 15:40
This is usually a sign of a corrupted database. Please try restoring a backup and see if this fixes the issue.

**Comment by cybermcm** [comment] 2021-07-25 06:23
I use watchtower to update my docker images in my lab environment. Most of the time this works, but sometimes the same happens to my MariaDB.
Workaround: stop container -> edit custom.cnf and add  `innodb_force_recovery = 6` -> restart -> stop container -> revert custom.cnf -> start again....
I checked Watchtower config, it uses SIGTERM which should be fine and I also updated timeout to 30 sec.

I noticed that there is `/etc/services.d/mariadb/run` where the db gets restarted if SIGTERM is sent. Can this be the issue? Watchtower sends SIGTERM, db stops and gets restarted and then watchtower terminates the docker image after 30 sec (10 by default) when the db is actually running again?

**Comment by cybermcm** [comment] 2021-08-08 12:34
@MxD-js: another possible solution: Did you check libseccomp?
Check this https://docs.linuxserver.io/faq#libseccomp, especially if you use RaspianOS.

**Comment by leranp** [comment] 2021-08-28 05:53
> The issue is due to
> 
> ```
> 2021-08-26 15:00:25 0 [ERROR] InnoDB: Upgrade after a crash is not supported. The redo log was created with MariaDB 10.4.21.
> ```
> 
> Your database wasn't shut down cleanly before the switch to the new image. Because it's a version jump that necessitates an upgrade it fails as it cannot upgrade a dirty DB.
> 
> You need to roll back to 110.4.21, _cleanly_ shut down the container, and then the upgrade to latest will run successfully.

Tried to rollback to 110.4.21 and everything works fine, than i stopped the container and update to latest version , but the problem persist 
Can you please help me? I'm with docker compose

Thank in advance

**Comment by leranp** [comment] 2021-08-28 06:54
I found the solution for the problem.
Enter to the container with " exec mariadb /bin/bash"
And then "mysql_upgrade -u root -p"
Enter your sql password and after the update the problem is fixed for me at least

**Comment by derekoharrow** [comment] 2021-09-02 16:09
> The issue is due to
> 
> ```
> 2021-08-26 15:00:25 0 [ERROR] InnoDB: Upgrade after a crash is not supported. The redo log was created with MariaDB 10.4.21.
> ```
> 
> Your database wasn't shut down cleanly before the switch to the new image. Because it's a version jump that necessitates an upgrade it fails as it cannot upgrade a dirty DB.
> 
> You need to roll back to 110.4.21, _cleanly_ shut down the container, and then the upgrade to latest will run successfully.

Worked for me - thanks!

**Comment by axute** [comment] 2021-09-30 11:47
sorry i will never use this image again, looks for me that data is away, bad migration guys.

**Comment by j0nnymoe** [comment] 2021-09-30 12:01
@axute Thank you for the unhelpful comment.

Closing issue as it's been resolved.

**Closed by j0nnymoe** 2021-09-30 12:01 UTC
