### ISSUE TITLE
MariaDB update to 10.2 or higher

### ISSUE THREAD

**Issue by Dominik-1980** [linuxserver/docker-mariadb#71] opened 2021-01-30 23:45 UTC
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

**Comment by Roxedus** [comment] 2021-01-30 23:47
Dupe of #70 #68 #62 #60 #47 and #45

**Closed by Roxedus** 2021-01-30 23:47 UTC

**Comment by nemchik** [comment] 2021-02-12 00:26
We have released the `:alpine` tag which now includes 10.5 for all CPU types. This will eventually be released as the `:latest` tag and will be noted in the changelog in the readme.
