### ISSUE TITLE
[BUG] MySQL/MariaDB: Storage Error/Corrupt DB error on improperly upgraded engine in Authelia 4.37.3

### ISSUE THREAD

**Issue by masterwishx** [linuxserver/docker-mariadb#111] opened 2022-12-09 10:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

MySQL/MariaDB: Storage Error/Corrupt DB error on improperly upgraded engine after updated Authelia to 4.37.3
This issue fixed when run 'mysql_upgrade -u root -p' in MariaDB Docker console
https://github.com/authelia/authelia/issues/4519
https://mariadb.com/kb/en/mysql_upgrade/

### Expected Behavior

'mysql_upgrade -u root -p' command
should be run after autoupdate docker MariaDB

### Steps To Reproduce

update Authelia to 4.37.3
but its MariaDB upate problem

### Environment

```markdown
Unraid 6.11.5

MariaDB Docker latest version :MySQL: 5.5.5-10.6.10-MariaDB-log с PHP-расширением MySQLi
```

### CPU architecture

x86-64

### Docker creation

```bash
Unraid Docker
```

### Container logs

```bash
...
```

**Comment by HannesJo0139** [comment] 2022-12-09 11:14
Just came here for the same reason. The official mariadb image offers the env var `MARIADB_AUTO_UPGRADE` and allows for auto check if `mysql_upgrade/mariadb-upgrade` is needed. Having such a thing here would be nice.

**Comment by james-d-elliott** [comment] 2022-12-09 11:22
To add to the context of producing this, a user would (likely) have to automatically upgrade (or manually without knowing there is an additional required step) to a new minor version i.e. from 10.4.x to 10.5.x for this to occur (according to the MariaDB/MySQL docs). The problem is that MySQL/MariaDB do not force users to upgrade like PostgreSQL does it seems.

It is in my opinion a bad practice (and probably the opinion of many other informed individuals) for this upgrade (regardless of engine) to occur automatically as failures in this process could lead to a catastrophic corruption of the database. 

As per both the MySQL and MariaDB documentation it is recommended users backup ALL of their databases prior to using `mysql_upgrade` or `mariadb_upgrade`.

**Comment by HannesJo0139** [comment] 2022-12-09 11:26
Hmm, then it may be another idea to have a startup check that throws an information in the container log when an upgrade is necessary.

**Comment by thespad** [comment] 2022-12-09 11:33
FWIW we've discussed doing this previously, but it's tricky to automate in such a way that we don't risk accidentally hosing someone's install when they blindly autoupdate to a newer version.

If we can find a reliable way to detect that it's required, we might be able to add instructions to the container log (not that people read them) for people to perform the mysql_upgrade process themselves.

**Comment by james-d-elliott** [comment] 2022-12-09 11:52
There is *probably* a way via `mysqlcheck` as `mysql_upgrade` just runs several `mysqlcheck` commands and a single `mysql` command. I'm thinking `mysqlcheck --all-databases` may be suitable according to [the docs](https://mariadb.com/kb/en/mysqlcheck/), but I'm not by any means an expert.

**Comment by thespad** [comment] 2022-12-09 11:53
We'll give it a look.

**Comment by masterwishx** [comment] 2022-12-09 18:22
@thespad 
> we've discussed doing this previously, but it's tricky to automate in such a way that we don't risk accidentally hosing someone's install when they blindly autoupdate to a newer version.

like @HannesJo0139 said above MariaDB Official Dcoker have :  

MARIADB_AUTO_UPGRADE / MARIADB_DISABLE_UPGRADE_BACKUP env , and its making backup befor if you not disable it .
is it not good way to add this env in this container also ?

**Comment by nemchik** [comment] 2022-12-09 18:39
The official docker image (which is maintained by the Docker organization, not specifically the MariaDB team, just an FYI) has a very complicated entrypoint. This approach is significantly different to how our image is built. I can't speak to the validity of their method, but there are just enough risks involved in their method that we feel more comfortable providing documentation and logging messages about how to run the upgrade command as opposed to providing a way for the container to silently perform this action without user knowledge. Sure you would have to have opted to use the variable to enable the behavior, but after that point you would have no idea when it runs.

We're still working through adjusting our image to check if an upgrade is required, log a message, and also to update our readme.

**Comment by masterwishx** [comment] 2022-12-09 19:35
> We're still working through adjusting our image to check if an upgrade is required, log a message, and also to update our readme.

Thanks, I got it.

**Comment by masterwishx** [comment] 2023-01-01 11:56
> We're still working through adjusting our image to check if an upgrade is required, log a message, and also to update our readme.

Sorry for offtop here, i just was interested another question :
is any specific reason we dont have the last version of mariaDB like 10.10.2 and using 10.6.10 for now ?

**Comment by thespad** [comment] 2023-01-01 13:03
Because we use the packages provided by the Alpine repos. Right now that's 10.6.10 https://pkgs.alpinelinux.org/packages?name=mariadb&branch=v3.16

Even if we rebased to Alpine 3.17 we'd still only gain one point release https://pkgs.alpinelinux.org/packages?name=mariadb&branch=v3.17

**Comment by masterwishx** [comment] 2023-01-01 13:08
> Because we use the packages provided by the Alpine repos.

OK, Thanks i got it

**Comment by nemchik** [comment] 2023-02-01 03:19
I'm going to close this now as we have merged https://github.com/linuxserver/docker-mariadb/pull/112 which logs a message to the container logs if an upgrade is required. If no upgrade is required, nothing is logged.

**Closed by nemchik** 2023-02-01 03:19 UTC
Labels: no-issue-activity
