### ISSUE TITLE
Container stops right after creation

### ISSUE THREAD

**Issue by PuckeyP** [linuxserver/docker-mariadb#108] opened 2022-10-03 15:59 UTC
Hi All,
Trying to get the mariadb container running, but it stops working right after spinning up the container

```
sudo docker run	--name=MariaDB \
				-d \
  				linuxserver/mariadb \
 				-p 3308:3306 \
				-v /volume1/docker/MariaDB/Data:/config \
  				-e PUID=1026 \
  				-e PGID=100 \
				-e TZ=Europe/Amsterdam \
  				-e MYSQL_ROOT_PASSWORD="xxxxxx" \
  				-e MYSQL_DATABASE="JPProef" \
  				-e MYSQL_USER="jpep" \
  				-e MYSQL_PASSWORD= "xxxxxx" \
 				--restart unless-stopped
```

Portainer gives the log below

```
You can start the MariaDB daemon with:
cd '/usr' ; /usr/bin/mysqld_safe --datadir='/config/databases'
You can test the MariaDB daemon with mysql-test-run.pl
cd '/usr/mysql-test' ; perl mysql-test-run.pl
Please report any problems at https://mariadb.org/jira
The latest information about MariaDB is available at https://mariadb.org/.
Consider joining MariaDB's strong and vibrant community:
https://mariadb.org/get-involved/
2022-10-03 15:39:42 0 [Note] mysqld (mysqld 10.5.17-MariaDB-log) starting as process 135 ...
2022-10-03 15:39:43 0 [Note] InnoDB: Uses event mutexes
2022-10-03 15:39:43 0 [Note] InnoDB: Compressed tables use zlib 1.2.12
2022-10-03 15:39:43 0 [Note] InnoDB: Number of pools: 1
2022-10-03 15:39:43 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
2022-10-03 15:39:43 0 [Note] InnoDB: Using Linux native AIO
2022-10-03 15:39:43 0 [Note] InnoDB: Initializing buffer pool, total size = 268435456, chunk size = 134217728
2022-10-03 15:39:43 0 [Note] InnoDB: Completed initialization of buffer pool
2022-10-03 15:39:43 0 [Note] InnoDB: 128 rollback segments are active.
2022-10-03 15:39:43 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2022-10-03 15:39:43 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2022-10-03 15:39:43 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2022-10-03 15:39:43 0 [Note] InnoDB: 10.5.17 started; log sequence number 45106; transaction id 20
2022-10-03 15:39:43 0 [Note] Plugin 'FEEDBACK' is disabled.
2022-10-03 15:39:43 0 [Note] InnoDB: Loading buffer pool(s) from /config/databases/ib_buffer_pool
2022-10-03 15:39:43 0 [Note] InnoDB: Buffer pool(s) load completed at 221003 15:39:43
2022-10-03 15:39:43 0 [Note] Server socket created on IP: '::'.
2022-10-03 15:39:43 0 [Note] Reading of all Master_info entries succeeded
2022-10-03 15:39:43 0 [Note] Added new Master_info '' to hash table
2022-10-03 15:39:43 0 [Note] mysqld: ready for connections.
Version: '10.5.17-MariaDB-log'  socket: '/run/mysqld/mysqld.sock'  port: 3306  MariaDB Server
2022-10-03 15:39:45 0 [Note] mysqld (initiated by: root[root] @ localhost []): Normal shutdown
2022-10-03 15:39:45 0 [Note] Event Scheduler: Purging the queue. 0 events
2022-10-03 15:39:45 0 [Note] InnoDB: FTS optimize thread exiting.
2022-10-03 15:39:45 0 [Note] InnoDB: Starting shutdown...
2022-10-03 15:39:45 0 [Note] InnoDB: Dumping buffer pool(s) to /config/databases/ib_buffer_pool
2022-10-03 15:39:45 0 [Note] InnoDB: Buffer pool(s) dump completed at 221003 15:39:45
2022-10-03 15:39:45 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
2022-10-03 15:39:45 0 [Note] InnoDB: Shutdown completed; log sequence number 45118; transaction id 23
2022-10-03 15:39:45 0 [Note] mysqld: Shutdown complete
Database Setup Completed
#################################################################
# No root password or too short a password ,min of 4 characters #
# No root password will be set, this is not a good thing        #
# You shoud set one after initialisation with the command       #
#          mysqladmin -u root password <PASSWORD>               #
#################################################################
cont-init: info: /etc/cont-init.d/40-initialise-db exited 0
cont-init: info: running /etc/cont-init.d/99-custom-files
[custom-init] No custom files found, skipping...
cont-init: info: /etc/cont-init.d/99-custom-files exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-mods: starting
s6-rc: info: service init-mods successfully started
s6-rc: info: service init-mods-package-install: starting
s6-rc: info: service init-mods-package-install successfully started
s6-rc: info: service init-mods-end: starting
s6-rc: info: service init-mods-end successfully started
s6-rc: info: service init-services: starting
s6-rc: info: service init-services successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun mariadb (no readiness notification)
s6-rc: info: service legacy-services successfully started
s6-rc: info: service 99-ci-service-check: starting
[ls.io-init] done.
s6-rc: info: service 99-ci-service-check successfully started
/run/s6/basedir/scripts/rc.init: line 42: -p: not found
s6-rc: info: service 99-ci-service-check: stopping
s6-rc: info: service 99-ci-service-check successfully stopped
s6-rc: info: service legacy-services: stopping
Caught SIGTERM signal!
cat: /var/run/mysqld/mysqld.pid: No such file or directory
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service init-services: stopping
s6-rc: info: service 00-legacy: stopping
s6-rc: info: service init-services successfully stopped
s6-rc: info: service init-mods-end: stopping
s6-rc: info: service 00-legacy successfully stopped
s6-rc: info: service init-mods-end successfully stopped
s6-rc: info: service init-mods-package-install: stopping
s6-rc: info: service init-mods-package-install successfully stopped
s6-rc: info: service init-mods: stopping
s6-rc: info: service init-mods successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
221003 15:39:51 mysqld_safe Logging to '/config/databases/e7607ecd8238.err'.
221003 15:39:51 mysqld_safe Starting mariadbd daemon with databases from /config/databases
```

What am I doing wrong?
PPee

**Comment by PuckeyP** [comment] 2022-10-03 17:05
If I do that
```
sudo docker run	--name=MariaDB \
				-d \
 				-p 3308:3306 \
				-v /volume1/docker/MariaDB/Data:/config \
  				-e PUID=1026 \
  				-e PGID=100 \
				-e TZ=Europe/Amsterdam \
  				-e MYSQL_ROOT_PASSWORD="xxxxx" \
  				-e MYSQL_DATABASE="JPProef" \
  				-e MYSQL_USER="jpep" \
  				-e MYSQL_PASSWORD= "xxxxx" \
 				--restart unless-stopped \
				linuxserver/mariadb
```

Then I get this:
<img width="485" alt="Screenshot 2022-10-03 at 19 03 43" src="https://user-images.githubusercontent.com/18032897/193636544-a50514c5-cf82-4265-af2a-d0fb9374a22a.png">

**Comment by aptalca** [comment] 2022-10-03 17:23
you have a space after the mysql password env var

in any case, closing this because it is not a bug. You can use our discord or discourse for support requests

**Closed by aptalca** 2022-10-03 17:23 UTC
