### ISSUE TITLE
Unable to set max_allowed_packet

### ISSUE THREAD

**Issue by angdigi** [linuxserver/docker-mariadb#46] opened 2020-02-09 18:57 UTC
Setting max_allowed_packet in docker command results in
`unknown flag: --max_allowed_packet`

Here is run command

`root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='mariadb' --net='eth0' --ip='10.100.0.3' --log-opt max-size='50m' --log-opt max-file='1' -e TZ="America/New_York" -e HOST_OS="Unraid" -e 'TCP_PORT_3306'='3306' -e 'PUID'='99' -e 'PGID'='100' -v '/mnt/user/appdata/mariadb':'/config':'rw' --max_allowed_packet=64M 'linuxserver/mariadb' 
unknown flag: --max_allowed_packet
See 'docker run --help'.

The command failed.`

Expected max_allowed_packet size to increase to 64M instead of default 16M

**Comment by aptalca** [comment] 2020-02-09 19:08
That's not a recognized docker flag. Not sure what you're trying to do, but it is not a bug report, so I'm closing this.

**Closed by aptalca** 2020-02-09 19:08 UTC

**Comment by angdigi** [comment] 2020-02-09 19:14
The setting is located in the config.cnf file. Mysql dockers can make this change so I assumed mariadb could as well. My mistake.

https://stackoverflow.com/questions/39369367/increase-max-allowed-packet-size-in-mysql-docker

**Comment by aptalca** [comment] 2020-02-09 19:22
Even with those mysql images, the way you passed the parameter wouldn't work. They need it as a `command`, not a `docker argument`.

Anyway, our mariadb image provides a config file at `/config/custom.cnf` that is user configurable. Explained in the readme: https://github.com/linuxserver/docker-mariadb#application-setup

**Comment by kenorb** [comment] 2022-09-20 22:43
> --max_allowed_packet=64M

You need to pass argument after the name of Docker image, not before. For example:

    docker run -e MYSQL_ROOT_PASSWORD=root --rm -p 3306:3306 mysql:5.7.39 --max-allowed-packet=1G --sql-mode=""

**Comment by alexfornuto** [comment] 2024-03-19 17:56
To anyone else for whom searching returned this issue as a top result: if you're using docker compose (or even if you're not, really), you can edit `custom.cnf` in the volume mounted to `/config` and edit the `max_allowed_packet` value there.
